apiVersion: v1
kind: Scenario
metadata:
  name: testrollback
spec:
  conditions:
    express: Equal
    #USE Equal, NotEqual, Greater, GreaterOrEqual, Smaller, SmallerOrEqual
    value: "reverse"
    operands:
      type: DDS
      name: gear_state
      value: "rt/piccolo/gear_state"
  action:
    - operation: update
      image: sdv.lge.com/library/passive-redundant-pong:0.1