apiVersion: v1
kind: Scenario
metadata:
  name: rollback-sample
spec:
  conditions:
    express: Equal
    #USE Equal, NotEqual, Greater, GreaterOrEqual, Smaller, SmallerOrEqual
    value: "reverse"
    operands:
    - type: DDS
      name: gear_state
      value: "rt/piccolo/gear_state"
  action: rollback
  - image: "sdv.lge.com/smart_trailer:0.1"
