# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: bms-mavd
  annotations:
    io.piccolo.annotations.package-type: default
    io.piccolo.annotations.package-name: bms
    io.piccolo.annotations.package-network: default
  labels:
    app: bms-mavd
spec:
  hostNetwork: true
  containers:
    - name: mavd
      image: localhost/mavd:1.0
  terminationGracePeriodSeconds: 0
