# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: welcome-honda
  labels:
    app: welcome-honda
spec:
  hostNetwork: true
  containers:
    - name: welcome-honda
      image: sdv.lge.com/demo/tg-welcome-honda:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
