version: "3"
services:
  yamlparser:
    network_mode: "host"
    build: ./
    command: /piccolo-bluechi/yamlparser
    volumes:
      - /root/piccolo_yaml:/root/piccolo_yaml
      - ./doc/examples/scenario:/piccolo-bluechi/example
  api-server:
    network_mode: "host"
    build: ./
    command: /piccolo-bluechi/api-server
  statemanager:
    network_mode: "host"
    build: ./
    command: /piccolo-bluechi/statemanager
    volumes:
      - /root/piccolo_yaml:/root/piccolo_yaml
      - /run/dbus:/run/dbus
      - /etc/containers/systemd:/etc/containers/systemd
  etcd:
    network_mode: "host"
    image: gcr.io/etcd-development/etcd:v3.5.11
    command: >
        /usr/local/bin/etcd
        --data-dir=/etcd-data
        --listen-peer-urls http://10.159.57.33:2380
        --advertise-client-urls http://10.159.57.33:2379
        --listen-client-urls http://10.159.57.33:2379
    volumes:
      - ./etcd-data:/etcd-data
#  gateway:
#    network_mode: "host"
#    image: sdv.lge.com/library/xxxxxxx:0.x
#    command: /gateway
#    volumes:
#      - /etcd_storage:/etcd_storage