# SPDX-License-Identifier: Apache-2.0

#HOST_IP=0.0.0.0
#GUEST_SSH_IP=192.168.50.239:22
#;if you fix YAML_STORAGE, to fix Makefile is also needed. (make install)
#YAML_STORAGE=/root/piccolo_yaml
#HOST_NODE=HPC
#GUEST_NODE=ZONE
#GUEST_NODE_ID=root
#GUEST_NODE_PW=lge123
#DOC_REGISTRY=http://0.0.0.0:41234
#;more items will be added

yaml_storage: /root/piccolo_yaml
doc_registry: http://0.0.0.0:41234
host:
  name: HPC
  ip: 0.0.0.0
guest:
  - name: ZONE
    ip: 192.168.50.239
    ssh_port: 22
    id: root
    pw: lge123
