# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

services:
  yamlparser:
    network_mode: "host"
    container_name: piccolo-yamlparser
    build:
      context: ../
      dockerfile: ./containers/Dockerfile
    command: /piccolo-bluechi/yamlparser
    volumes:
      - /root/piccolo_yaml:/root/piccolo_yaml
      - ../doc/examples/scenario:/piccolo-bluechi/example
  api-server:
    network_mode: "host"
    container_name: piccolo-apiserver
    build:
      context: ../
      dockerfile: ./containers/Dockerfile
    command: /piccolo-bluechi/api-server
  statemanager:
    network_mode: "host"
    container_name: piccolo-statemanager
    build:
      context: ../
      dockerfile: ./containers/Dockerfile
    command: /piccolo-bluechi/statemanager
    volumes:
      - /root/piccolo_yaml:/root/piccolo_yaml
      - /run/dbus:/run/dbus
      - /etc/containers/systemd:/etc/containers/systemd
  etcd:
    network_mode: "host"
    container_name: piccolo-etcd
    image: gcr.io/etcd-development/etcd:v3.5.11
    command: >
        /usr/local/bin/etcd
        --data-dir=/etcd-data
        --listen-peer-urls http://10.157.19.218:2380
        --advertise-client-urls http://10.157.19.218:2379
        --listen-client-urls http://10.157.19.218:2379
    volumes:
      - ../etcd-data:/etcd-data
  gateway:
    network_mode: "host"
    container_name: piccolo-gateway
    build:
      context: ../
      dockerfile: ./containers/Dockerfile-gateway
    command: /root/gateway_for_bluechi/build/PiccoloGateway
    environment:
      - HOST_IP=10.157.19.218
