apiVersion: v1
kind: Scenario
metadata:
  name: test
spec:
  conditions:
    express: Equal
    #USE Equal, NotEqual, Greater, GreaterOrEqual, Smaller, SmallerOrEqual
    value: "parking"
    operands:
      type: DDS
      name: gear_state
      value: "rt/piccolo/gear_state"
  action:
    - operation: update
      image: sdv.lge.com/library/passive-redundant-pong:0.2

--------------------

send gRPC message
  scenario/update-sample                      (scenario/{name})

category: PiccoloEvent                        (not yet)
action: scenario/update-sample/action         (key/{action})
conditions: scenario/update-sample/conditions  (key/{conditions})


--key--
scenario/update-sample/conditions

--value--
---
express: Equal
value: "parking"
operands:
  - type: DDS
    name: gear_state
    value: "rt/piccolo/gear_state"


--key--
scenario/update-sample/action

--value--
---
operation: update
image: sdv.lge.com/library/passive-redundant-pong:0.2
