# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: welcome-oterhs
  labels:
    app: welcome-others
spec:
  hostNetwork: true
  containers:
    - name: welcome-others
      image: sdv.lge.com/demo/tg-welcome-default:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
