# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: welcome-tesla
  labels:
    app: welcome-tesla
spec:
  hostNetwork: true
  containers:
    - name: welcome-tesla
      image: sdv.lge.com/demo/tg-welcome-tesla:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
