# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Scenario
metadata:
  name: bms
spec:
  conditions:
    express: eq
    value: P
    operands:
      type: DDS
      name: gear
      value: PowertrainTransmissionCurrentGear
  actions:
    - operation: update
  targets:
    - package: bms-algorithm-eco
