# SPDX-License-Identifier: Apache-2.0

services:
  piccolo-nginx:
    image: nginx
    ports:
      - "41234:80"
    volumes:
      - ../resources/:/usr/share/piccolo/resources:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf