apiVersion: v1
kind: Scenario
metadata:
  name: version-display
spec:
  conditions:
  action:
    - operation: deploy
      spec:
        containers:
        - name: display-container
          image: sdv.lge.com/library/version_display:1.0
          volumeMounts:
          - name: x11
            mountPath: /tmp/.X11-unix
          env:
          - name: DISPLAY
            value: :0
        volumes:
        - name: x11
          hostPath:
            path: /tmp/.X11-unix

