apiVersion: v1
kind: Scenario
metadata:
  name: version-display
spec:
  conditions:
    express: Equal
    value: "reverse"
    operands:
      type: DDS
      name: gear_state
      value: "rt/piccolo/gear_state"
  actions:
    - operation: rollback
      podSpec:
        containers:
        - name: display-container
          image: sdv.lge.com/library/version_display:1.0
          volumeMounts:
          - name: x11
            mountPath: /tmp/.X11-unix
          env:
          - name: DISPLAY
            value: :0
        volumes:
        - name: x11
          hostPath:
            path: /tmp/.X11-unix
