# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Scenario
metadata:
  name: version-display
spec:
  conditions:
    express: Equal
    value: "parking"
    operands:
      type: DDS
      name: gear_state
      value: "rt/piccolo/gear_state"
  actions:
    - operation: update
      podSpec:
        containers:
        - name: display-container
          image: sdv.lge.com/library/version_display:2.0
          volumeMounts:
          - name: x11
            mountPath: /tmp/.X11-unix
          env:
          - name: DISPLAY
            value: :0
        volumes:
        - name: x11
          hostPath:
            path: /tmp/.X11-unix
