# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: welcome-kgm
  labels:
    app: welcome-kgm
spec:
  hostNetwork: true
  containers:
    - name: welcome-kgm
      image: sdv.lge.com/demo/tg-welcome-kgmobility:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
