# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: welcome-hyundai
  labels:
    app: welcome-hyundai
spec:
  hostNetwork: true
  containers:
    - name: welcome-hyundai
      image: sdv.lge.com/demo/tg-welcome-hyundai:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
