# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: welcome-gm
  labels:
    app: welcome-gm
spec:
  hostNetwork: true
  containers:
    - name: welcome-gm
      image: sdv.lge.com/demo/tg-welcome-gm:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
